# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HobbyMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HobbyMe

  target 'HobbyMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HobbyMeUITests' do
    # Pods for testing
  end

end
